### ISSUE TITLE
vlfeat bug at compilation on Ubuntu 20.04 

### ISSUE THREAD

**Issue by pierre33** [CNES/cars#1]
Hi Cars Team,

I open this issue to warn about a known bug when we try to compile vlfeat on Ubuntu 20.04. It has been highlighted [here](https://github.com/vlfeat/vlfeat/issues/214) and reproduced by vlfeat team. I just asked them if there is any workaround.
Pierre L

**Comment by pierre33** [comment]
Fixed by removing all default(None) in file vl/kmeans.c [here](https://github.com/vlfeat/vlfeat/issues/214)

**Comment by duboise-cnes** [comment]
Thanks for the issue and the workaround with vlfeat team. With Latex installation (my case), the compilation is breaking also and works with : 
`make MEX=$MATLABROOT/bin/`
See https://github.com/vlfeat/vlfeat/issues/76

**Comment by dyoussef** [comment]
Fixed here : https://github.com/CNES/cars/blob/master/Dockerfile#L93
