### ISSUE TITLE
The config file does not really read the name of the .geom files

### ISSUE THREAD

**Issue by DhDeepLIT** [CNES/cars#20]
steps to reproduce:
copy 
img1.tif -> img1_vib.tif
img2.tif -> img2_vib.tif
img3.tif -> img3_vib.tif

modify config file to set file name correctly but keep names of the .geom files:
```

"inputs": {
            "sensors" : {
                "one": {
                    "image": "img1_vib.tif",
                    "geomodel": "img1.geom"
                },
                "two": {
                    "image": "img2_vib.tif",
                    "geomodel": "img2.geom"
                },
                "three": {
                    "image": "img3_vib.tif",
                    "geomodel": "img3.geom"
```

run config and itk/otb complain that it cannot build a "model"

```
23-09-28 16:45:58 :: PROGRESS :: Check configuration...
23-09-28 16:45:59 :: PROGRESS :: CARS pipeline is started.
23-09-28 16:46:00 :: PROGRESS :: Data list to process: [  ] ...
Tiles processing: : 0it [00:00, ?it/s]
23-09-28 16:46:00 :: ERROR :: CARS terminated with following error
Traceback (most recent call last):
  File "/cars/venv/lib/python3.8/site-packages/cars/cars.py", line 175, in main_cli
    used_pipeline.run()
  File "/cars/venv/lib/python3.8/site-packages/cars/pipelines/sensor_to_dense_dsm/sensor_to_dense_dsm_pipeline.py", line 459, in run
    ) = self.epipolar_grid_generation_application.run(
  File "/cars/venv/lib/python3.8/site-packages/cars/applications/grid_generation/epipolar_grid_generation.py", line 214, in run
    ) = projection.get_ground_angles(config, self.geometry_loader)
  File "/cars/venv/lib/python3.8/site-packages/cars/core/projection.py", line 836, in get_ground_angles
    lat1_0, lon1_0, alt1_0, lat1, lon1, alt1 = get_ground_direction(
  File "/cars/venv/lib/python3.8/site-packages/cars/core/projection.py", line 762, in get_ground_direction
    lat0, lon0, alt0 = geometry_loader.direct_loc(
  File "/cars/venv/lib/python3.8/site-packages/cars/core/geometry/otb_geometry.py", line 430, in direct_loc
    s2c_app.Execute()
  File "/usr/local/otb/lib/otb/python/otbApplication.py", line 2315, in Execute
    return _otbApplication.Application_Execute(self)
RuntimeError: Exception thrown in otbApplication Application_Execute: /cars/otb_remote_module/app/otbConvertSensorToGeoPointFast.cxx:161:
itk::ERROR: Unable to create a model
```

To solve problem:
copy 
img1.geom -> img1_vib.geom
img2.geom -> img2_vib.geom 
img3.geom -> img3_vib.geom

and keep WRONG config file ... it will work as a charm...

**Comment by dyoussef** [comment]
Hello,

Today, we're in transition between two libraries for geometry management: OTB and SHARELOC. Using SHARELOC is motivated by the fact that cars will soon be fully installable with pip (pip install cars): we're almost there (see https://cars.readthedocs.io/en/stable/install.html). OTB automatically retrieves the geometric model from the image, but this will no longer be the case with SHARELOC. We wanted a more explicit way of working, as it was often a source of user error.

In fact, in the "OTB" case, the files must have the same name: myimage.tif and myimage.geom. 
We'll see if we can get closer to the way shareloc works with the Extended filenames (https://www.orfeo-toolbox.org/CookBook/ExtendedFilenames.html#reader-options).

Thank you for your feedback, we'll keep you informed
Regards,
David

**Comment by dyoussef** [comment]
The tool is now fully installable with pip. The geom model is now well taken into account by shareloc, but we won't be doing any specific development. If you have any other problems, please do not hesitate to contact us.
