### ISSUE TITLE
Open data images

### ISSUE THREAD

**Issue by MordicusEtCubitus** [CNES/cars#4]
Hi,

is there open data images that can be downloaded to test the library ?
Could you provide such url ?

Thanks in advance,

Gaël,

**Comment by duboise-cnes** [comment]
Hello, 
You can find some raw little images in tests/ directory . 

Otherwise, satellite images can be found in different places such as : 
https://sentinel.esa.int/web/sentinel/sentinel-data-access
https://peps.cnes.fr/rocket/#/home

Hoping it helps. 
Cordially,

**Comment by duboise-cnes** [comment]
I close the issue with the previous answer
